# This job listens for new releases and will build the appropriate artifacts
# and upload them to the release.

name: Release

on:
  push:
    branches:
      - develop*

permissions:
  contents: write

jobs:
  build-upload:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    -
      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: build Docker image
      run: make -f Makefile.host.mk build_docker
    - name: build binary
      run: make -f Makefile.host.mk build_binary
    - name: pack product
      run: make -f Makefile.host.mk pack_product
    - 
      name: upload 
      uses: actions/upload-artifact@v3
      with:
        name: lmbench3_artifact.zip
        path: ./lmbench3_*.zip
